label: "//tensorboard/projector:standalone_lib"
src {
  longpath: "org_tensorflow_tensorboard/tensorboard/projector/standalone_lib.html"
  path: "tensorboard/projector/standalone_lib.html"
  webpath: "/standalone_lib.html"
}
src {
  longpath: "org_tensorflow_tensorboard/tensorboard/projector/standalone_projector_config.json"
  path: "tensorboard/projector/standalone_projector_config.json"
  webpath: "/standalone_projector_config.json"
}
src {
  longpath: "org_tensorflow_tensorboard/tensorboard/projector/standalone_bundle.js"
  path: "bazel-out/k8-fastbuild/bin/tensorboard/projector/standalone_bundle.js"
  webpath: "/standalone_bundle.js"
}
