name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0
          working-directory: '${{ github.workspace }}/docs'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site/